### PR TITLE
Bundling Feature

### PR DESCRIPTION
**Pull request by jpfranco**
Changes include:

- Script bundling (concatenation) feature.
- Removed LiveRail plugin
- Added iframe HTML.
- Added YouTube plugin (although it's currently disabled until issue with `encodingPriority` is fixed).
- Updated wording in the wizard, sample page and readme.

### CODE REVIEW

**Comment by mistermendez** [comment]
I am running into issues with - "eslint-config-airbnb": "^13.0.0", after I run `npm install` and `npm test`. Using node 5.0.

```
ESLint couldn't find the plugin "eslint-plugin-jsx-a11y". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-jsx-a11y is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-jsx-a11y@latest --save-dev


npm WARN EPEERINVALID eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
npm WARN EPEERINVALID eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-import@^2.1.0 but none was installed.
npm WARN EPEERINVALID eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none was installed.
npm WARN EPEERINVALID eslint-config-airbnb-base@10.0.1 requires a peer of eslint-plugin-import@^2.1.0 but none was installed.
```

**Comment by mistermendez** [comment]
I also get this message at the end of download. Do I need to create this dir? `/Users/jmendez/repos/oppm/dist`

```
Failed to create .zip package. Please make sure you have write permissions on the destination folder.
```

**Comment by mistermendez** [comment]
After creating `dist` dir, downloaded .zip and sample.htm page work

**Comment by jpfranco** [comment]
@mistermendez I hadn't run into that eslint issue before, let me try doing a clean install. Which node version were you using?

The dist folder is only used in dev environment, but I think I removed the line that created it automatically. I'll put that back in.

**Comment by mistermendez** [comment]
I'm using Node 5

**Comment by jpfranco** [comment]
@mistermendez done. I fixed the eslint dependencies and included the dist folder.

**Comment by mistermendez** [comment]
sweet, verified both issues resolved 👍

**Pull request merged**
